# Inventory file
# This is where I will be storing information about the server and it's IP-adress or hostname.

[nextcloud]
localhost ansible_connection=local      # server IP here. I have localhost for now because I am already connected to the server via ssh

[coturn]
localhost ansible_connection=local      # server IP here. I have localhost for now because I am already connected to the server via ssh